name: Update README Lio17-lab

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Necesario para hacer push

    steps:
      - uses: actions/checkout@v4

      - name: Set up config
        run: |
          mkdir -p .github
          echo "MAX_LINES: 5" > .github/recent-activity.config.yml

      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git diff --quiet README.md || {
            git add README.md
            git commit -m "🔄 Auto-update README [skip ci]"
            git push
          }
